# Assignment 2

In [441]:
import numpy as np
import pandas as pd

### 1. Employee Salary Adjustment

In [442]:
salaries = np.array([45000, 52000, 61000, 48000, 75000])
salaries

array([45000, 52000, 61000, 48000, 75000])

##### a. Increase all salaries by 10%.

In [443]:
incremented_salaries = salaries + salaries / 10
incremented_salaries

array([49500., 57200., 67100., 52800., 82500.])

##### b. Find the average salary.

In [444]:
print(f'Average salary before increment: {salaries.mean()}')
print(f'Average salary after increment: {incremented_salaries.mean()}')

Average salary before increment: 56200.0
Average salary after increment: 61820.0

##### c. Find the maximum and minimum salary.

In [445]:
print('Maximum and Minimum Salaries Before Increment')
print(f'Minimum Salary: {salaries.min()}')
print(f'Maximum Salary: {salaries.max()}')

print()

print('Maximum and Minimum Salaries After Increment')
print(f'Minimum Salary: {incremented_salaries.min()}')
print(f'Maximum Salary: {incremented_salaries.max()}')

Maximum and Minimum Salaries Before Increment
Minimum Salary: 45000
Maximum Salary: 75000

Maximum and Minimum Salaries After Increment
Minimum Salary: 49500.0
Maximum Salary: 82500.0

##### d. Print salaries greater than 60000

In [446]:
salaries_greater_than_60k = salaries[salaries > 60000]
print(f'Salaries greater than 60K before increment: {salaries_greater_than_60k}')

print()

salaries_greater_than_60k = incremented_salaries[incremented_salaries > 60000]
print(f'Salaries greater than 60K after increment: {salaries_greater_than_60k}')

Salaries greater than 60K before increment: [61000 75000]

Salaries greater than 60K after increment: [67100. 82500.]

### 2. Sales Data Analysis

Daily sales of a store for 10 days:

In [447]:
sales = np.array([120,150,180,200,170,160,210,220,190,175])
sales

array([120, 150, 180, 200, 170, 160, 210, 220, 190, 175])

##### a. Compute total sales

In [448]:
total_sales = sales.sum()
print(f'Total Sales: {total_sales}')

Total Sales: 1775

##### b. Compute mean and standard deviation

In [449]:
sales_mean = sales.mean()
sales_sd = sales.std()

print(f'Sales Mean = {sales_mean}')
print(f'Sales Standard Deviation = {sales_sd}')

Sales Mean = 177.5
Sales Standard Deviation = 28.217902119044926

##### c. Identify days where sales exceeded the average.

In [450]:
days_with_sales_more_than_avg = np.where(sales > sales_mean)[0]
print(f'Days when sales exceeded the average: ')
for day in days_with_sales_more_than_avg:
  print(f'Day {day + 1}', end = ', ')

Days when sales exceeded the average:
Day 3, Day 4, Day 7, Day 8, Day 9,

##### d. Normalize the sales using Min-Max scaling.

In [451]:
sales_min = sales.min()
sales_max = sales.max()

sales_normalized = (sales - sales_min) / (sales_max - sales_min)

print(sales_normalized)

[0.   0.3  0.6  0.8  0.5  0.4  0.9  1.   0.7  0.55]

### 3. Matrix Operations for Business Data

A company has sales data for 3 products across 4 regions.

In [452]:
sales_matrix = np.array([
[120,140,130,150],
[80,90,100,95],
[200,210,190,205]
])

##### a. Find total sales per product.

In [453]:
total_sales_per_product = sales_matrix.sum(axis=1)
total_sales_per_product
for i in range(total_sales_per_product.size):
  print(f'Total sales for Product {i + 1} = {total_sales_per_product[i]}')

Total sales for Product 1 = 540
Total sales for Product 2 = 365
Total sales for Product 3 = 805

##### b. Find total sales per region.

In [454]:
total_sales_per_region = sales_matrix.sum(axis=0)
total_sales_per_region
for i in range(total_sales_per_region.size):
  print(f'Total sales for Region {i + 1} = {total_sales_per_region[i]}')

Total sales for Region 1 = 400
Total sales for Region 2 = 440
Total sales for Region 3 = 420
Total sales for Region 4 = 450

##### c. Identify the best performing product.

In [455]:
print('Best performing products: ')
best_performing_products = np.where(total_sales_per_product == total_sales_per_product.max())[0]
for product_index in best_performing_products:
  print(f'Product {product_index + 1}')

Best performing products:
Product 3

##### d. Identify the region with highest sales.

In [456]:
print('Regions with highest sale: ')
highest_sale_regions = np.where(total_sales_per_region == total_sales_per_region.max())[0]
for region_index in highest_sale_regions:
  print(f'Region {region_index + 1}')

Regions with highest sale:
Region 4

### 4. Employee Dataset Exploration

In [457]:
data = {
'Employee':['A','B','C','D','E','F'],
'Department':['HR','IT','IT','Finance','HR','Finance'],
'Salary':[50000,65000,70000,72000,52000,68000],
'Experience':[2,5,7,6,3,4]
}

##### a. Convert this dictionary into a DataFrame.

In [458]:
employee_df = pd.DataFrame(data)
employee_df

  Employee Department  Salary  Experience
0        A         HR   50000           2
1        B         IT   65000           5
2        C         IT   70000           7
3        D    Finance   72000           6
4        E         HR   52000           3
5        F    Finance   68000           4

##### b. Display basic statistics of the dataset.

In [459]:
employee_df.describe()

             Salary  Experience
count      6.000000    6.000000
mean   62833.333333    4.500000
std     9474.527253    1.870829
min    50000.000000    2.000000
25%    55250.000000    3.250000
50%    66500.000000    4.500000
75%    69500.000000    5.750000
max    72000.000000    7.000000

In [460]:
employee_df.groupby('Department')['Employee'].count()

Department
Finance    2
HR         2
IT         2
Name: Employee, dtype: int64

##### c. Find the average salary per department.

In [461]:
employee_df.groupby('Department')['Salary'].mean().rename('Average_Salary')

Department
Finance    70000.0
HR         51000.0
IT         67500.0
Name: Average_Salary, dtype: float64

##### d. Identify employees with experience greater than 4 years.

In [462]:
employee_df[employee_df['Experience'] > 4]

  Employee Department  Salary  Experience
1        B         IT   65000           5
2        C         IT   70000           7
3        D    Finance   72000           6

##### e. Add a new column Bonus = 10% of salary.

In [463]:
employee_df['Bonus'] = employee_df['Salary'] * 0.1
employee_df

  Employee Department  Salary  Experience   Bonus
0        A         HR   50000           2  5000.0
1        B         IT   65000           5  6500.0
2        C         IT   70000           7  7000.0
3        D    Finance   72000           6  7200.0
4        E         HR   52000           3  5200.0
5        F    Finance   68000           4  6800.0

### 5. Missing Data Handling

In [464]:
data_new = {
'Name':['John','Anna','Peter','Linda','David'],
'Age':[28, np.nan, 35, 32, np.nan],
'Salary':[50000,54000,np.nan,58000,60000]
}

In [465]:
new_emp_df = pd.DataFrame(data_new)
new_emp_df

    Name   Age   Salary
0   John  28.0  50000.0
1   Anna   NaN  54000.0
2  Peter  35.0      NaN
3  Linda  32.0  58000.0
4  David   NaN  60000.0

##### a. Detect missing values.

In [466]:
new_emp_df.isna().sum()

Name      0
Age       2
Salary    1
dtype: int64

In [467]:
new_emp_df.isnull().sum()

Name      0
Age       2
Salary    1
dtype: int64

##### b. Replace missing Age with mean age.

In [468]:
new_emp_df['Age'] = new_emp_df['Age'].fillna(new_emp_df['Age'].mean())

In [469]:
new_emp_df

    Name        Age   Salary
0   John  28.000000  50000.0
1   Anna  31.666667  54000.0
2  Peter  35.000000      NaN
3  Linda  32.000000  58000.0
4  David  31.666667  60000.0

In [470]:
new_emp_df.isna().sum()

Name      0
Age       0
Salary    1
dtype: int64

##### c. Replace missing Salary with median salary

In [471]:
new_emp_df['Salary'] = new_emp_df['Salary'].fillna(new_emp_df['Salary'].median())
new_emp_df

    Name        Age   Salary
0   John  28.000000  50000.0
1   Anna  31.666667  54000.0
2  Peter  35.000000  56000.0
3  Linda  32.000000  58000.0
4  David  31.666667  60000.0

In [472]:
new_emp_df.isna().sum()

Name      0
Age       0
Salary    0
dtype: int64

##### d. Remove rows with any remaining missing values.

There're no more rows with missing values. However, if there's any we can use the following function:

In [473]:
new_emp_df.dropna()
new_emp_df

    Name        Age   Salary
0   John  28.000000  50000.0
1   Anna  31.666667  54000.0
2  Peter  35.000000  56000.0
3  Linda  32.000000  58000.0
4  David  31.666667  60000.0

### 6. Sales Performance Analysis

In [474]:
sales_data = {
'Region':['North','South','East','West','North','South','East','West'],
'Salesperson':['A','B','C','D','E','F','G','H'],
'Sales':[12000,15000,13000,17000,16000,14000,15500,16500]
}

converting to data frames

In [475]:
sales_df = pd.DataFrame(sales_data)
sales_df

  Region Salesperson  Sales
0  North           A  12000
1  South           B  15000
2   East           C  13000
3   West           D  17000
4  North           E  16000
5  South           F  14000
6   East           G  15500
7   West           H  16500

##### a. Find total sales per region.

In [476]:
sales_df.groupby('Region')['Sales'].sum().rename('Total Sales')

Region
East     28500
North    28000
South    29000
West     33500
Name: Total Sales, dtype: int64

##### b. Identify the top salesperson.

In [477]:
sales_df[sales_df['Sales'] == sales_df['Sales'].max()]

  Region Salesperson  Sales
3   West           D  17000

##### c. Compute average sales across regions.

In [478]:
sales_df.groupby('Region')['Sales'].mean().rename('Average Sales')

Region
East     14250.0
North    14000.0
South    14500.0
West     16750.0
Name: Average Sales, dtype: float64

##### d. Sort the dataset by sales descending.

In [479]:
sales_df.sort_values('Sales', ascending = False)

  Region Salesperson  Sales
3   West           D  17000
7   West           H  16500
4  North           E  16000
6   East           G  15500
1  South           B  15000
5  South           F  14000
2   East           C  13000
0  North           A  12000

### 7. Customer Purchase Analysis

In [480]:
cust_data = {
'CustomerID':[101,102,103,104,105,106,107],
'Age':[25,45,35,50,23,40,60],
'PurchaseAmount':[250,600,400,800,150,700,900],
'City':['Delhi','Mumbai','Delhi','Chennai','Mumbai','Delhi','Chennai']
}

Converting to data frame:

In [481]:
cust_df = pd.DataFrame(cust_data)
cust_df

   CustomerID  Age  PurchaseAmount     City
0         101   25             250    Delhi
1         102   45             600   Mumbai
2         103   35             400    Delhi
3         104   50             800  Chennai
4         105   23             150   Mumbai
5         106   40             700    Delhi
6         107   60             900  Chennai

##### a. Find the average purchase amount by city.

In [482]:
cust_df.groupby('City')['PurchaseAmount'].mean().rename('Average Purchase Amount')

City
Chennai    850.0
Delhi      450.0
Mumbai     375.0
Name: Average Purchase Amount, dtype: float64

##### b. Identify customers with purchase above overall average.

In [483]:
#mean purchase amount
mean_purchase_amount = cust_df['PurchaseAmount'].mean()
print(f'Mean Purchase Amount = {mean_purchase_amount}')

Mean Purchase Amount = 542.8571428571429

In [484]:
cust_df[cust_df['PurchaseAmount'] > mean_purchase_amount]

   CustomerID  Age  PurchaseAmount     City
1         102   45             600   Mumbai
3         104   50             800  Chennai
5         106   40             700    Delhi
6         107   60             900  Chennai

##### c. Find the city generating the highest revenue.

In [485]:
city_revenues = cust_df.groupby('City')['PurchaseAmount'].sum()
city_revenues

City
Chennai    1700
Delhi      1350
Mumbai      750
Name: PurchaseAmount, dtype: int64

Highest Revenue generating Cities:

In [486]:
city_revenues[city_revenues == city_revenues.max()]

City
Chennai    1700
Name: PurchaseAmount, dtype: int64

##### d. Create a column Age_Group:

*   <30 → Young
*   30 – 50 → Adult
*   \>50 → Senior

In [487]:
age_bins = [0, 30, 50, float('inf')]
age_labels = ['Young', 'Adult', 'Senior']
cust_df['Age_Group'] = pd.cut(cust_data['Age'], bins = age_bins, labels = age_labels, right = False)
cust_df

   CustomerID  Age  PurchaseAmount     City Age_Group
0         101   25             250    Delhi     Young
1         102   45             600   Mumbai     Adult
2         103   35             400    Delhi     Adult
3         104   50             800  Chennai    Senior
4         105   23             150   Mumbai     Young
5         106   40             700    Delhi     Adult
6         107   60             900  Chennai    Senior

##### e. Find average purchase per age group.

In [488]:
cust_df.groupby('Age_Group', observed=True)['PurchaseAmount'].mean().rename('Average Purchase Amount')

Age_Group
Young     200.000000
Adult     566.666667
Senior    850.000000
Name: Average Purchase Amount, dtype: float64

### 8. Time Series Sales Analysis

Generate data:

In [489]:
dates = pd.date_range('2024-01-01', periods=12, freq='M')
sales = [200,220,250,270,300,320,350,360,380,400,420,450]
df = pd.DataFrame({'Date':dates,'Sales':sales})

/tmp/ipykernel_193/4035140013.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range('2024-01-01', periods=12, freq='M')

##### a. Convert Date to datetime index.

In [490]:
df.set_index('Date', inplace = True)
df

            Sales
Date
2024-01-31    200
2024-02-29    220
2024-03-31    250
2024-04-30    270
2024-05-31    300
2024-06-30    320
2024-07-31    350
2024-08-31    360
2024-09-30    380
2024-10-31    400
2024-11-30    420
2024-12-31    450

##### b. Compute monthly percentage growth.

In [491]:
df['MonthlyPercentageGrowth'] = df['Sales'].pct_change() * 100
df

            Sales  MonthlyPercentageGrowth
Date
2024-01-31    200                      NaN
2024-02-29    220                10.000000
2024-03-31    250                13.636364
2024-04-30    270                 8.000000
2024-05-31    300                11.111111
2024-06-30    320                 6.666667
2024-07-31    350                 9.375000
2024-08-31    360                 2.857143
2024-09-30    380                 5.555556
2024-10-31    400                 5.263158
2024-11-30    420                 5.000000
2024-12-31    450                 7.142857

##### c. Calculate 3-month rolling average sales.

In [492]:
df['3M_Rolling_Avg'] = df['Sales'].rolling(window=3).mean()
df

            Sales  MonthlyPercentageGrowth  3M_Rolling_Avg
Date
2024-01-31    200                      NaN             NaN
2024-02-29    220                10.000000             NaN
2024-03-31    250                13.636364      223.333333
2024-04-30    270                 8.000000      246.666667
2024-05-31    300                11.111111      273.333333
2024-06-30    320                 6.666667      296.666667
2024-07-31    350                 9.375000      323.333333
2024-08-31    360                 2.857143      343.333333
2024-09-30    380                 5.555556      363.333333
2024-10-31    400                 5.263158      380.000000
2024-11-30    420                 5.000000      400.000000
2024-12-31    450                 7.142857      423.333333

##### d. Identify the month with highest growth rate.

In [493]:
df[df['MonthlyPercentageGrowth'] == df['MonthlyPercentageGrowth'].max()]

            Sales  MonthlyPercentageGrowth  3M_Rolling_Avg
Date
2024-03-31    250                13.636364      223.333333